# Generated by Django 4.1.7 on 2023-04-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0011_alter_education_end_date_and_more'),
        ('organization', '0003_employmenttenure_employmenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('days_taken', models.PositiveIntegerField(default=0)),
                ('current_balance', models.PositiveIntegerField(default=0)),
                ('upcoming_balance_update_date', models.DateTimeField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField()),
                ('must_be_earned', models.BooleanField(default=False)),
                ('earned_after', models.SmallIntegerField(default=0)),
                ('is_carry_forward', models.BooleanField()),
                ('total_days', models.PositiveSmallIntegerField(null=True)),
                ('minimum_days', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Verified', 'Verified'), ('Approved', 'Approved'), ('Preapproved', 'Preapproved'), ('Granted', 'Granted'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], db_index=True, default='Requested', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employee.employee')),
                ('leave_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='leave.leavebalance')),
                ('leave_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leave.leavepolicy')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_leave_requests', to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequestStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('action', models.CharField(choices=[('Verifier', 'Verifier'), ('Preapprover', 'Preapprover'), ('Approver', 'Approver'), ('Granter', 'Granter')], db_index=True, max_length=15)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Verified', 'Verified'), ('Approved', 'Approved'), ('Preapproved', 'Preapproved'), ('Granted', 'Granted'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], db_index=True, default='Requested', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_leave_requests', to='employee.employee')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwared_leave_requests', to='employee.employee')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='leave.leaverequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='salary_scales',
            field=models.ManyToManyField(related_name='leave_policies', to='organization.salaryscale'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_leave_balances', to='leave.leavepolicy'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='leave.leaverequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveProcessManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_process', models.CharField(choices=[('Verifier', 'Verifier'), ('Preapprover', 'Preapprover'), ('Approver', 'Approver'), ('Granter', 'Granter')], db_index=True, max_length=15)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_manager', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_managers', to='employee.employee')),
            ],
            options={
                'unique_together': {('employee', 'leave_process')},
            },
        ),
        migrations.CreateModel(
            name='LeavePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_entitled', models.PositiveSmallIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('leave_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave.leavepolicy')),
            ],
            options={
                'unique_together': {('employee', 'leave_policy')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_policy')},
        ),
    ]
