# Generated by Django 4.1.7 on 2023-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='category',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
