# Generated by Django 4.1.7 on 2023-04-12 14:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='county',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='parish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('postcode', models.CharField(default=None, max_length=5)),
                ('code', models.CharField(default=None, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parish',
                'verbose_name_plural': 'Parishes',
            },
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='village',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=None, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='location.parish')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
            },
        ),
        migrations.CreateModel(
            name='subcounty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=None, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='location.county', to_field='vote_code')),
            ],
            options={
                'verbose_name': 'Sub County',
                'verbose_name_plural': 'Sub Counties',
            },
        ),
        migrations.CreateModel(
            name='sub_region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='location.region', to_field='code')),
            ],
            options={
                'verbose_name': 'Sub Region',
                'verbose_name_plural': 'Sub Regions',
            },
        ),
        migrations.AddField(
            model_name='parish',
            name='subcounty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='location.subcounty', to_field='code'),
        ),
        migrations.CreateModel(
            name='local_government',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_code', models.CharField(default=None, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default=None, max_length=100)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='location.district', to_field='code')),
            ],
            options={
                'verbose_name': 'Local Governments',
                'verbose_name_plural': 'Local Government',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='sub_region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='location.sub_region', to_field='code'),
        ),
        migrations.AddField(
            model_name='county',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='location.district', to_field='code'),
        ),
        migrations.AddField(
            model_name='county',
            name='local_gov',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='location.local_government', to_field='vote_code'),
        ),
    ]
