# Generated by Django 4.1.7 on 2023-04-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='parish',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='location.parish', to_field='code'),
        ),
    ]
