# Generated by Django 4.1.7 on 2023-04-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_employmenttenure_employmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attachment',
            field=models.FileField(upload_to='uploads/events/'),
        ),
    ]
