# Generated by Django 4.1.7 on 2023-03-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
     
     
      
        migrations.AddField(
            model_name='district',
            name='sub_region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='common.subregion'),
        ),
        migrations.AddField(
            model_name='county',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='common.district'),
        ),
        migrations.AddField(
            model_name='county',
            name='local_gov',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='common.localgovernment'),
        ),
    ]
