# Generated by Django 4.1.7 on 2023-04-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='sub_region',
        ),
        migrations.RemoveField(
            model_name='localgovernment',
            name='district',
        ),
        migrations.RemoveField(
            model_name='parish',
            name='subcounty',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='county',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='region',
        ),
        migrations.RemoveField(
            model_name='village',
            name='parish',
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='district',
        ),
        migrations.DeleteModel(
            name='LocalGovernment',
        ),
        migrations.DeleteModel(
            name='Parish',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='SubCounty',
        ),
        migrations.DeleteModel(
            name='SubRegion',
        ),
        migrations.DeleteModel(
            name='village',
        ),
    ]
