# Generated by Django 4.1.7 on 2023-03-28 07:54

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0003_employmenttenure_employmenttype'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_supervisory', models.BooleanField()),
                ('probation_period', models.PositiveSmallIntegerField(default=6)),
                ('job_summary', models.TextField(blank=True)),
                ('job_description', models.TextField(blank=True)),
                ('max_holders', models.PositiveSmallIntegerField(default=1)),
                ('employment_tenure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_tenure', to='organization.employmenttenure')),
                ('employment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_type', to='organization.employmenttype')),
                ('headed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.designation')),
                ('org_unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orgunit', to='organization.unit')),
                ('salary_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.salaryscale')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('dob', models.DateField(validators=[common.validators.validate_user_birth_date])),
                ('contract_duration', models.IntegerField(blank=True, null=True)),
                ('salutation', models.CharField(choices=[('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.'), ('Dr', 'Dr.'), ('Eng', 'Eng.'), ('Prof', 'Prof.'), ('Hon', 'Hon.')], default='Mr', max_length=15)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=15)),
                ('employee_number', models.CharField(blank=True, max_length=50)),
                ('probation_period', models.PositiveSmallIntegerField(default=3)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(null=True, upload_to='uploads/appointment_letters/')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='employee.designation')),
                ('employment_tenure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization.employmenttenure')),
                ('employment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization.employmenttype')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.nationality')),
                ('salary_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.salaryscale')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='underlings', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.village')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
