# Generated by Django 4.1.7 on 2023-04-12 09:28

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_duration',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_tenure',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='probation_period',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary_scale',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='village',
        ),
        migrations.AddField(
            model_name='designation',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='othernames',
            field=models.CharField(default='none', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profilePic',
            field=models.FileField(blank=True, null=True, upload_to='uploads/profilePic/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(default='none', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.'), ('Dr', 'Dr.'), ('Eng', 'Eng.'), ('Prof', 'Prof.'), ('Hon', 'Hon.')], default='Ms', max_length=15),
        ),
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(default=None, max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('date_of_birth', models.DateField(blank=True, max_length=150, null=True)),
                ('nin', models.CharField(blank=True, max_length=14, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian')], max_length=150)),
                ('is_nok', models.BooleanField(default=False)),
                ('is_dependant', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(default=None, max_length=15)),
                ('address', models.CharField(default=None, max_length=255)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50)),
                ('org_name', models.CharField(blank=True, max_length=50)),
                ('org_website', models.CharField(blank=True, max_length=50)),
                ('org_telephone', models.CharField(blank=True, max_length=50)),
                ('org_email', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='employee.employee')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('qualification_title', models.CharField(blank=True, max_length=150)),
                ('qualification_Level', models.CharField(blank=True, choices=[('Post-Doctorate', 'Post-Doctorate'), ('Doctorate', 'Doctorate'), ('Masters', 'Masters'), ('PGD', 'post Graduate Diploma'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('UACE', 'Advanced Certificate of Education'), ('UCE', 'Ordinary Certificate of Education'), ('PLE', 'Primary Leaving Examination Certificate')], max_length=50)),
                ('institution_name', models.CharField(blank=True, max_length=150)),
                ('institution_website', models.CharField(blank=True, max_length=150)),
                ('institution_address', models.TextField(blank=True)),
                ('institution_email', models.EmailField(blank=True, max_length=254)),
                ('qualification_description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('graduation_date', models.DateField()),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='employee.employee')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('contact_type', models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Residential', 'Residential')], max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.CharField(default=None, max_length=15)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='employee.employee')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('accountName', models.CharField(max_length=25)),
                ('accountNumber', models.IntegerField()),
                ('bankName', models.CharField(max_length=25)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(default=None, max_length=15)),
                ('district', models.CharField(default=None, max_length=15)),
                ('county', models.CharField(default=None, max_length=15)),
                ('subcounty', models.CharField(default=None, max_length=15)),
                ('parish', models.CharField(blank=True, max_length=15)),
                ('village', models.CharField(blank=True, max_length=15)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='employee.employee')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
