# Generated by Django 4.1.7 on 2023-04-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_email_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
