# Generated by Django 4.1.7 on 2023-04-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_employeenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
