# Generated by Django 4.1.7 on 2023-04-13 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation_supervisor', to='employee.designation'),
        ),
    ]
