# Generated by Django 4.1.7 on 2023-04-18 10:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_employmenttenure_employmenttype'),
        ('employee', '0009_alter_designation_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.CharField(choices=[('Substantive', 'Substantive'), ('Acting', 'Acting')], max_length=20)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='appointment_letters/')),
                ('first_appointment', models.BooleanField(default=False)),
                ('current_appointment', models.BooleanField(default=False)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_designation', to='employee.designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='employee.employee')),
                ('employment_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organization.employmenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
