# Generated by Django 4.1.7 on 2023-04-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_website',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
