# Generated by Django 4.1.7 on 2023-04-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation_supervisor', to='employee.employee'),
        ),
    ]
