# Generated by Django 4.1.7 on 2023-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalperformancefactor',
            name='scores',
            field=models.IntegerField(),
        ),
    ]
